#!/bin/bash

EXECUTABLE=./JackCompiler

cp -r /autograder/submission/* /autograder/source/

pushd /autograder/source/ >/dev/null

# remove any jack, vm, or xml files in submission
rm -f *.jack *.xml *.vm

# run student-submitted setup script (untrusted)
chmod +x ./setup.sh
runuser -u student -- ./setup.sh

# in case setup.sh created jack or xml files
rm -f *.jack *.xml

chmod ugo+x "${EXECUTABLE}"

popd >/dev/null

# diff outputs with expected
cd /autograder/grader
uv run src/run_tests.py
